/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.userstory.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.userstory.services.UserStoryGrammarAccess;

@SuppressWarnings("all")
public class UserStorySyntacticSequencer extends AbstractSyntacticSequencer {

	protected UserStoryGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Us___ScenarioKeyword_15_0_ColonKeyword_15_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (UserStoryGrammarAccess) access;
		match_Us___ScenarioKeyword_15_0_ColonKeyword_15_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUsAccess().getScenarioKeyword_15_0()), new TokenAlias(false, false, grammarAccess.getUsAccess().getColonKeyword_15_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Us___ScenarioKeyword_15_0_ColonKeyword_15_1__q.equals(syntax))
				emit_Us___ScenarioKeyword_15_0_ColonKeyword_15_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('Scenario' ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     activity=usActivity (ambiguity) 'Given' artifact=usArtifact
	 *     activity=usActivity (ambiguity) 'Then' Event=usEvent
	 *     activity=usActivity (ambiguity) 'When' Event=usEvent
	 *     activity=usActivity (ambiguity) 'coming' 'from' activity1=[usActivity|ID]
	 *     activity=usActivity (ambiguity) (rule end)
	 */
	protected void emit_Us___ScenarioKeyword_15_0_ColonKeyword_15_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
